[package]
name = "domain-recon-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "*"
serde = { version = "1.0", features = ["derive"] }
reqwest = { version = "0.11", features = ["json"] } # reqwest with JSON parsing support
tokio = { version = "1.0.2", features = ["full"] }
exitfailure = "0.5.1"
async-std-resolver = "*"
futures = "*"
